### ISSUE TITLE
Ron think there will be a major problem with react.

### ISSUE THREAD

**Issue by smallwood-d** [smallwood-d/GBG#17]

**Comment by rbbaron** [comment]
we need to check the react freamwork,
we need to check if the framwork supplies all our needs in our project (services, classes),
i will check it and update.

**Comment by smallwood-d** [comment]
What does it mean services and classes?

בתאריך 3 בנוב' 2017 22:53,‏ "rbbaron" <notifications@github.com> כתב:

we need to check the react freamwork,
we need to check if the framwork supplies all our needs in our project
(services, classes),
i will check it and update.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SmallWood-D/GBG/issues/17#issuecomment-341824174>, or mute
the thread

**Comment by smallwood-d** [comment]
# We move to angular 2!
