### ISSUE TITLE
Decide on docs convention.

### ISSUE THREAD

**Issue by smallwood-d** [smallwood-d/GBG#2]
Do you think handling most of the requirements decisions in the issues is ok?
Do we need branch for it or the develop branch will do?

**Comment by duckflyer** [comment]
It seems OK to keep working on develop but possibly start with using branches for document changes. `deveop` and `master` imply stability but we are now all sort of working on the same thing and stability is not an issue.

I'm not very familiar with issues in GitHub if it is similar to TFS work items then I think we should find another solution. I'm afraid we won't be able to structure the document and that as more issues will be opened we will lose the requirements, I don't want people to have to go through pages of issues to get to the requirements.

**Comment by duckflyer** [comment]
We can consider the wiki feature, instead of creating the documents separately. It is still markdown though.

**Comment by smallwood-d** [comment]
The wiki is just md doc or more similar to real wikipedia page?

**Comment by duckflyer** [comment]
I think it's lighter but it is more than a md doc. You can check out
Microsoft's wiki here
https://github.com/Microsoft/TypeScript/wiki

**Comment by smallwood-d** [comment]
Itbseem tge wiki can ve ok for our needs.
So the only thing left is to collect requirements.
