### ISSUE TITLE
Does GBG will be interactive?

### ISSUE THREAD

**Issue by smallwood-d** [smallwood-d/GBG#6]
* Will I be able to play with the graph?
  * Will changes in the graph effect my repository?
  * Will I be able to config the graphs and change their appearance?
  * Will my graph will change in real-time?

**Comment by duckflyer** [comment]
I answered 'yes' to all items. I think we should also consider thre order
we try to meet these requirements.

**Comment by smallwood-d** [comment]
I will try organize some of the requirements in the file and later transfer it to wiki.
